spring:
  jackson:
    mapper:
      default-view-inclusion: true
  profiles:
    active:
      dev
  datasource:
    url:
      jdbc:h2:mem:app;DB_CLOSE_ON_EXIT=FALSE
    username:
      sa
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 725984848177-a2j2u673nn1gb912mku0k9qe762ikgl6.apps.googleusercontent.com
            client-secret: JCLQB32uWdgAN6FBepbqqQLe
          facebook:
            client-id: 410043406474015
            client-secret: 4d020bd87e29aab5fa5a68ff827faee2
  mail:
    host:
      smtp.gmail.com
    port:
      587
    username:
      noreplyrionup@gmail.com
    password:
      crmcsdjqkkvansiy
    properties:
      mail:
        smtp:
          auth:
            true
          starttls:
            enable:
              true
  servlet:
    multipart:
      max-file-size:
        10MB
server:
  ssl:
    key-store:
      classpath:keystore.p12
    key-store-password:
      changeit
    keyStoreType:
      PKCS12
    keyAlias:
      tomcat
  port:
    9000

react:
  server:
    port:
      3000
    host:
      localhost
aws:
  s3:
    credentials:
      path:
        /home/ubuntu/aws/s3/credentials